version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true

run:
  timeout: 5m
